name: ddev-d9
networks:
  ddev_default:
    external: true
    name: ddev_default
  default:
    name: ddev-d9_default
services:
  web:
    build:
      args:
        BASE_IMAGE: drud/ddev-webserver:v1.19.0-1
        gid: "1000"
        uid: "1000"
        username: parallels
      context: /home/parallels/workspace/d9/.ddev/web-build
      dockerfile: ../.webimageBuild/Dockerfile
    image: drud/ddev-webserver:v1.19.0-1-d9-built
    restart: "no"
    user: 1000:1000
    volumes:
    - consistency: cached
      source: ../
      target: /var/www/html
      type: bind
    - bind:
        create_host_path: true
      read_only: true
      source: /home/parallels/workspace/d9/.ddev
      target: /mnt/ddev_config
      type: bind
    - bind:
        create_host_path: true
      read_only: true
      source: /home/parallels/workspace/d9/.ddev/xhprof
      target: /usr/local/bin/xhprof
      type: bind
    - source: ddev-global-cache
      target: /mnt/ddev-global-cache
      type: volume
      volume: {}
    - source: ddev-ssh-agent_socket_dir
      target: /home/.ssh-agent
      type: volume
      volume: {}
    working_dir: /var/www/html/
volumes:
  database:
    external: true
    name: d9-postgres
  ddev-global-cache:
    external: true
    name: ddev-global-cache
  ddev-ssh-agent_socket_dir:
    external: true
    name: ddev-ssh-agent_socket_dir
