name: ddev-d9
networks:
  ddev_default:
    external: true
    name: ddev_default
  default:
    name: ddev-d9_default
services:
  db:
    build:
      args:
        BASE_IMAGE: postgres:12
        gid: "999"
        uid: "1000"
        username: parallels
      context: /home/parallels/workspace/d9/.ddev/db-build
      dockerfile: ../.dbimageBuild/Dockerfile
    command:
    - -c
    - config_file=/etc/postgresql/postgresql.conf
    - -c
    - hba_file=/etc/postgresql/pg_hba.conf
    container_name: ddev-d9-db
    environment:
      COLUMNS: "80"
      DDEV_HOSTNAME: d9.ddev.site
      DDEV_PHP_VERSION: "7.4"
      DDEV_PRIMARY_URL: https://d9.ddev.site
      DDEV_PROJECT: d9
      DDEV_PROJECT_TYPE: drupal9
      DDEV_ROUTER_HTTP_PORT: "80"
      DDEV_ROUTER_HTTPS_PORT: "443"
      DDEV_SITENAME: d9
      DDEV_TLD: ddev.site
      DOCKER_IP: 127.0.0.1
      HOST_DOCKER_INTERNAL_IP: 172.17.0.1
      IS_DDEV_PROJECT: "true"
      LINES: "38"
      MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/d9-db/mysql_history
      MYSQL_PWD: db
      PGDATABASE: db
      PGHOST: localhost
      PGPASSWORD: db
      PGUSER: db
      POSTGRES_DB: db
      POSTGRES_PASSWORD: db
      POSTGRES_USER: db
      TZ: ""
    healthcheck:
      interval: 1s
      retries: 120
      start_period: 2m0s
      test:
      - CMD-SHELL
      - /postgres_healthcheck.sh
      timeout: 2m0s
    hostname: d9-db
    image: postgres:12-d9-built
    labels:
      com.ddev.app-type: drupal9
      com.ddev.approot: /home/parallels/workspace/d9
      com.ddev.platform: ddev
      com.ddev.site-name: d9
    networks:
      ddev_default: null
      default: null
    ports:
    - host_ip: 127.0.0.1
      mode: ingress
      protocol: tcp
      target: 5432
    restart: "no"
    stop_grace_period: 1m0s
    user: 999:999
    volumes:
    - source: database
      target: /var/lib/postgresql/data
      type: volume
      volume:
        nocopy: true
    - bind:
        create_host_path: true
      source: /home/parallels/workspace/d9/.ddev
      target: /mnt/ddev_config
      type: bind
    - bind:
        create_host_path: true
      source: /home/parallels/workspace/d9/.ddev/db_snapshots
      target: /mnt/snapshots
      type: bind
    - source: ddev-global-cache
      target: /mnt/ddev-global-cache
      type: volume
      volume: {}
    working_dir: /var/lib/postgresql
  web:
    build:
      args:
        BASE_IMAGE: drud/ddev-webserver:v1.19.0-1
        gid: "1000"
        uid: "1000"
        username: parallels
      context: /home/parallels/workspace/d9/.ddev/web-build
      dockerfile: ../.webimageBuild/Dockerfile
    cap_add:
    - SYS_PTRACE
    container_name: ddev-d9-web
    environment:
      COLUMNS: "80"
      DDEV_DOCROOT: web
      DDEV_FILES_DIR: /var/www/html/web/sites/default/files
      DDEV_HOSTNAME: d9.ddev.site
      DDEV_PHP_VERSION: "7.4"
      DDEV_PRIMARY_URL: https://d9.ddev.site
      DDEV_PROJECT: d9
      DDEV_PROJECT_TYPE: drupal9
      DDEV_ROUTER_HTTP_PORT: "80"
      DDEV_ROUTER_HTTPS_PORT: "443"
      DDEV_SITENAME: d9
      DDEV_TLD: ddev.site
      DDEV_WEBSERVER_TYPE: apache-fpm
      DDEV_XDEBUG_ENABLED: "false"
      DEPLOY_NAME: local
      DOCKER_IP: 127.0.0.1
      DOCROOT: web
      DRUSH_ALLOW_XDEBUG: "1"
      DRUSH_OPTIONS_URI: https://d9.ddev.site
      HOST_DOCKER_INTERNAL_IP: 172.17.0.1
      HTTP_EXPOSE: 80:80,8025:8025
      HTTPS_EXPOSE: 443:80,8026:8025
      IS_DDEV_PROJECT: "true"
      LINES: "38"
      MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/d9-web/mysql_history
      MYSQL_PWD: db
      PGDATABASE: db
      PGHOST: db
      PGPASSWORD: db
      PGUSER: db
      PHP_IDE_CONFIG: serverName=d9.ddev.site
      SSH_AUTH_SOCK: /home/.ssh-agent/socket
      TZ: ""
      VIRTUAL_HOST: d9.ddev.site
    external_links:
    - ddev-router:d9.ddev.site
    extra_hosts:
    - host.docker.internal:172.17.0.1
    healthcheck:
      interval: 1s
      retries: 120
      start_period: 2m0s
      timeout: 2m0s
    hostname: d9-web
    image: drud/ddev-webserver:v1.19.0-1-d9-built
    labels:
      com.ddev.app-type: drupal9
      com.ddev.approot: /home/parallels/workspace/d9
      com.ddev.platform: ddev
      com.ddev.site-name: d9
    networks:
      ddev_default: null
      default: null
    ports:
    - host_ip: 127.0.0.1
      mode: ingress
      protocol: tcp
      target: 80
    - host_ip: 127.0.0.1
      mode: ingress
      protocol: tcp
      target: 443
    restart: "no"
    user: 1000:1000
    volumes:
    - consistency: cached
      source: ../
      target: /var/www/html
      type: bind
    - bind:
        create_host_path: true
      read_only: true
      source: /home/parallels/workspace/d9/.ddev
      target: /mnt/ddev_config
      type: bind
    - bind:
        create_host_path: true
      read_only: true
      source: /home/parallels/workspace/d9/.ddev/xhprof
      target: /usr/local/bin/xhprof
      type: bind
    - source: ddev-global-cache
      target: /mnt/ddev-global-cache
      type: volume
      volume: {}
    - source: ddev-ssh-agent_socket_dir
      target: /home/.ssh-agent
      type: volume
      volume: {}
    working_dir: /var/www/html/
volumes:
  database:
    external: true
    name: d9-postgres
  ddev-global-cache:
    external: true
    name: ddev-global-cache
  ddev-ssh-agent_socket_dir:
    external: true
    name: ddev-ssh-agent_socket_dir
