name: ddev-d9
services:
  web:
    build:
      args:
        BASE_IMAGE: drud/ddev-webserver:v1.19.0-1
        gid: "1000"
        uid: "1000"
        username: parallels
      context: /home/parallels/workspace/d9/.ddev/web-build
      dockerfile: ../.webimageBuild/Dockerfile
    image: drud/ddev-webserver:v1.19.0-1-d9-built
    restart: "no"
