name: ddev-d9
services:
  web:
    build:
      args:
        BASE_IMAGE: busybox
      context: /home/parallels/workspace/d9/.ddev/web-build
      dockerfile: ../.webimageBuild/Dockerfile
    image: busybox-built
